'use strict';

const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  DIRECTOR: 'DIRECTOR',
  MANAGER: 'MANAGER',
  RECEPTION: 'RECEPTION',
  SERVICE_STAFF: 'SERVICE_STAFF',
});

const ROLE_LIST = Object.values(ROLES);

const GUEST_STATUS = Object.freeze({
  EXPECTED: 'EXPECTED',
  CHECKED_IN: 'CHECKED_IN',
  CHECKED_OUT: 'CHECKED_OUT',
  NO_SHOW: 'NO_SHOW',
  CANCELLED: 'CANCELLED',
});

const GUEST_TYPE = Object.freeze({
  WALK_IN: 'WALK_IN',
  PRE_APPOINTED: 'PRE_APPOINTED',
});

const APPOINTMENT_STATUS = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  CONFIRMED: 'CONFIRMED',
  RESCHEDULED: 'RESCHEDULED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  NO_SHOW: 'NO_SHOW',
});

const ROOM_TYPE = Object.freeze({
  BOARDROOM: 'BOARDROOM',
  CONFERENCE: 'CONFERENCE',
  CABIN: 'CABIN',
  MEETING: 'MEETING',
  OTHER: 'OTHER',
});

const ROOM_STATUS = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  RESERVED: 'RESERVED',
  MAINTENANCE: 'MAINTENANCE',
});

const SERVICE_CATEGORY = Object.freeze({
  PANTRY: 'PANTRY',
  LOGISTICS: 'LOGISTICS',
  FACILITY: 'FACILITY',
  AV: 'AV',
  PARKING: 'PARKING',
  OTHER: 'OTHER',
});

const SERVICE_STATUS = Object.freeze({
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

const ID_TYPE = Object.freeze({
  EMIRATES_ID: 'EMIRATES_ID',
  PASSPORT: 'PASSPORT',
  DRIVING_LICENSE: 'DRIVING_LICENSE',
  OTHER: 'OTHER',
});

const NOTIFICATION_CHANNEL = Object.freeze({
  EMAIL: 'EMAIL',
  WHATSAPP: 'WHATSAPP',
  IN_APP: 'IN_APP',
});

const NOTIFICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
});

const NOTIFICATION_EVENT = Object.freeze({
  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  APPOINTMENT_INVITATION: 'APPOINTMENT_INVITATION',
  APPOINTMENT_REMINDER: 'APPOINTMENT_REMINDER',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  GUEST_CHECKED_IN: 'GUEST_CHECKED_IN',
  CHECK_IN_VISITOR: 'CHECK_IN_VISITOR',
  CHECK_IN_HOST: 'CHECK_IN_HOST',
  GUEST_CHECKED_OUT: 'GUEST_CHECKED_OUT',
  SERVICE_CREATED: 'SERVICE_CREATED',
  SERVICE_UPDATED: 'SERVICE_UPDATED',
  PASSWORD_EXPIRY_WARNING: 'PASSWORD_EXPIRY_WARNING',
  MAINTENANCE_NOTICE: 'MAINTENANCE_NOTICE',
  TRIAL_REMINDER: 'TRIAL_REMINDER',
  OFFICE_CREATED: 'OFFICE_CREATED',
});

const PAGINATION = Object.freeze({
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
});

module.exports = {
  ROLES,
  ROLE_LIST,
  GUEST_STATUS,
  GUEST_TYPE,
  APPOINTMENT_STATUS,
  ROOM_TYPE,
  ROOM_STATUS,
  SERVICE_CATEGORY,
  SERVICE_STATUS,
  ID_TYPE,
  NOTIFICATION_CHANNEL,
  NOTIFICATION_STATUS,
  NOTIFICATION_EVENT,
  PAGINATION,
  COUPON_TYPE: Object.freeze({ PERCENTAGE: 'PERCENTAGE', FLAT: 'FLAT' }),
  COUPON_STATUS: Object.freeze({ ACTIVE: 'ACTIVE', INACTIVE: 'INACTIVE', EXPIRED: 'EXPIRED' }),
  REFERRAL_STATUS: Object.freeze({
    PENDING: 'PENDING',
    SIGNED_UP: 'SIGNED_UP',
    CONVERTED: 'CONVERTED',
    REWARDED: 'REWARDED',
    EXPIRED: 'EXPIRED',
  }),
};